<?xml version="1.0" encoding="utf-8"?><Database Name="db" Class="dbSkyriseDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\db.mdf;Integrated Security=True;Connect Timeout=30;User Instance=True" SettingsObjectName="Skyrise.Properties.Settings" SettingsPropertyName="dbConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Telemetry" Member="Telemetries">
    <Type Name="Telemetry">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Latitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Longitude" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Altitude" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Satellites" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="AccX" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AccY" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="AccZ" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Heading" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="Pressure" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TempPressure" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Humidity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="TempHumidity" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Voltage" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Spin" Type="System.Double" DbType="Float" CanBeNull="true" />
    </Type>
  </Table>
  <Table Name="dbo.DebugLog" Member="DebugLogs">
    <Type Name="DebugLog">
      <Column Name="ID" Type="System.Int64" DbType="BigInt NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Timestamp" Type="System.DateTime" DbType="DateTime" CanBeNull="true" />
      <Column Name="Type" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="Description" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
      <Column Name="ErrorMessage" Type="System.String" DbType="VarChar(MAX)" CanBeNull="true" />
    </Type>
  </Table>
</Database>